version: "3"

services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: ${DB_PASS}
        ports:
        -   ${DB_PORT}:5432

    nginx:
        build: docker/nginx
        ports: 
            - ${API_PORT}:80
        volumes: 
            - ./backend:/app_b/

    php:
        build: docker/php
        volumes: 
            - ./backend:/app_b/

    # Used to generate backend api documentation during development
    swagger-cli:
        build: docker/swagger-cli
        volumes: 
            - ./backend:/app_b/
    

