version: "3"

services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: "${DB_PASS}"

    nginx:
        build: docker/nginx
        ports: 
            - ${API_PORT}:80
        volumes: 
            - ./backend:/app_b/
        links: 
            - php

    php:
        build: docker/php
        volumes: 
            - ./backend:/app_b/
    

