<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\db\ar\base;

use Yii;

/**
 * This is the base-model class for table "organization".
 *
 * @property integer $id
 * @property string $label
 *
 * @property \common\models\db\ar\EducationHistory[] $educationHistories
 * @property \common\models\db\ar\EmploymentHistory[] $employmentHistories
 * @property string $aliasModel
 */
abstract class Organization extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'organization';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['label'], 'required'],
            [['label'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'label' => Yii::t('models', 'Label'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEducationHistories()
    {
        return $this->hasMany(\common\models\db\ar\EducationHistory::className(), ['organization_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEmploymentHistories()
    {
        return $this->hasMany(\common\models\db\ar\EmploymentHistory::className(), ['organization_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\db\query\OrganizationQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\db\query\OrganizationQuery(get_called_class());
    }


}
